// Seed horses for the deck. Every profile is fictional.
export const SEED_HORSES = [
  {
    id: 'h1',
    name: 'Biscuit',
    age: 6,
    sex: 'Mare',
    breed: 'Quarter Horse',
    height: 15.1,
    coat: '#b5651d',
    mane: '#3b2412',
    stable: 'Willow Creek Stables',
    distance: 3,
    bio: 'Barrel racer by day, hay connoisseur by night. Will absolutely steal your carrots and feel zero remorse.',
    interests: ['Barrel racing', 'Carrots', 'Mud baths', 'Trail rides'],
    gait: 'Lope',
    lookingFor: 'A stallion who can keep up',
  },
  {
    id: 'h2',
    name: 'Thunderhoof',
    age: 9,
    sex: 'Stallion',
    breed: 'Friesian',
    height: 16.3,
    coat: '#1b1b1f',
    mane: '#0a0a0c',
    stable: 'Blackwater Farm',
    distance: 12,
    bio: 'Dramatic mane, dramatic personality. Looking for someone who appreciates a slow-motion gallop across a misty field.',
    interests: ['Dressage', 'Wind in my mane', 'Photo shoots', 'Apples'],
    gait: 'Trot',
    lookingFor: 'A mare who loves the spotlight too',
  },
  {
    id: 'h3',
    name: 'Daisy',
    age: 4,
    sex: 'Mare',
    breed: 'Welsh Pony',
    height: 12.2,
    coat: '#e8d9c0',
    mane: '#f3ede1',
    stable: 'Meadowlark Riding School',
    distance: 5,
    bio: 'Small but mighty. I teach kids to ride and I have never once been impressed by a jump under 2 feet.',
    interests: ['Kids', 'Peppermints', 'Naps in the sun', 'Gossip at the fence'],
    gait: 'Canter',
    lookingFor: 'Someone patient and sweet',
  },
  {
    id: 'h4',
    name: 'Copper',
    age: 7,
    sex: 'Gelding',
    breed: 'Thoroughbred',
    height: 16.1,
    coat: '#a0522d',
    mane: '#5a2d10',
    stable: 'Foxglove Downs',
    distance: 18,
    bio: 'Retired from the track, not from the fast life. Ex-racehorse seeking a companion for long walks and longer naps.',
    interests: ['Racing history', 'Sugar cubes', 'Rolling in dirt', 'Sunsets'],
    gait: 'Gallop',
    lookingFor: 'A pasture buddy',
  },
  {
    id: 'h5',
    name: 'Luna',
    age: 5,
    sex: 'Mare',
    breed: 'Andalusian',
    height: 15.3,
    coat: '#d8d8dc',
    mane: '#f0f0f2',
    stable: 'Silver Moon Equestrian',
    distance: 8,
    bio: 'Classically trained. I do piaffe when I get excited. My mane has its own conditioner routine.',
    interests: ['Dressage', 'Classical music', 'Grooming', 'Moonlit turnout'],
    gait: 'Trot',
    lookingFor: 'Elegance and good hooves',
  },
  {
    id: 'h6',
    name: 'Big Red',
    age: 11,
    sex: 'Gelding',
    breed: 'Belgian Draft',
    height: 18.0,
    coat: '#c1440e',
    mane: '#f5e6c8',
    stable: 'Old Oak Farm',
    distance: 22,
    bio: 'Gentle giant. Pulls carts, hearts, and the occasional stuck tractor. Feet the size of dinner plates.',
    interests: ['Pulling stuff', 'Oats', 'Belly rubs', 'Parades'],
    gait: 'Walk',
    lookingFor: 'Someone who does not mind sharing a stall',
  },
  {
    id: 'h7',
    name: 'Pepper',
    age: 3,
    sex: 'Mare',
    breed: 'Appaloosa',
    height: 14.3,
    coat: '#f1e9dc',
    mane: '#3a3a3a',
    stable: 'Spotted Sky Ranch',
    distance: 15,
    bio: 'Yes, the spots are real. No, you cannot count them. Young, spicy, and a little bit of a menace.',
    interests: ['Cattle sorting', 'Jumping fences (unauthorized)', 'Watermelon', 'Zoomies'],
    gait: 'Canter',
    lookingFor: 'A partner in crime',
  },
  {
    id: 'h8',
    name: 'Sir Reginald',
    age: 14,
    sex: 'Stallion',
    breed: 'Arabian',
    height: 15.0,
    coat: '#7a7a80',
    mane: '#d0d0d4',
    stable: 'Crescent Dunes Stud',
    distance: 30,
    bio: 'Distinguished. Endurance champion. I have opinions about hay quality and I will share them.',
    interests: ['Endurance riding', 'Fine alfalfa', 'Dust baths', 'Long conversations'],
    gait: 'Trot',
    lookingFor: 'A mare of refined taste',
  },
  {
    id: 'h9',
    name: 'Maple',
    age: 8,
    sex: 'Mare',
    breed: 'Haflinger',
    height: 14.1,
    coat: '#d4a24c',
    mane: '#fff6e0',
    stable: 'Sugarbush Hollow',
    distance: 6,
    bio: 'Golden coat, golden heart, flaxen mane that people literally stop to photograph. I like everyone and everyone likes me.',
    interests: ['Trail rides', 'Being petted', 'Apples', 'Mountain views'],
    gait: 'Walk',
    lookingFor: 'Good vibes only',
  },
  {
    id: 'h10',
    name: 'Bandit',
    age: 6,
    sex: 'Gelding',
    breed: 'Mustang',
    height: 14.2,
    coat: '#6b4423',
    mane: '#1e1208',
    stable: 'Free Range (technically)',
    distance: 40,
    bio: 'Born wild, gentled by choice. I can open any gate ever built. Do not test me on this.',
    interests: ['Escaping', 'Open range', 'Rolling in dirt', 'Wild oats'],
    gait: 'Gallop',
    lookingFor: 'Someone who values freedom',
  },
  {
    id: 'h11',
    name: 'Clementine',
    age: 10,
    sex: 'Mare',
    breed: 'Paint Horse',
    height: 15.0,
    coat: '#e3c5a0',
    mane: '#8b5a2b',
    stable: 'Two Rivers Ranch',
    distance: 9,
    bio: 'Patchwork coat, steady mind. I have carried three generations of one family and I am not done yet.',
    interests: ['Trail rides', 'Kids', 'Sunsets', 'Peppermints'],
    gait: 'Lope',
    lookingFor: 'Steady and kind',
  },
  {
    id: 'h12',
    name: 'Zephyr',
    age: 5,
    sex: 'Stallion',
    breed: 'Akhal-Teke',
    height: 15.2,
    coat: '#d9b45a',
    mane: '#b8902e',
    stable: 'Golden Steppe Stud',
    distance: 27,
    bio: 'My coat literally shimmers. Metallic sheen, no filter. Built for speed and looking fabulous doing it.',
    interests: ['Endurance riding', 'Photo shoots', 'Sunrise gallops', 'Grooming'],
    gait: 'Gallop',
    lookingFor: 'Someone who can handle the shine',
  },
  {
    id: 'h13',
    name: 'Muffin',
    age: 12,
    sex: 'Gelding',
    breed: 'Shetland Pony',
    height: 10.1,
    coat: '#5c3a21',
    mane: '#2a1a0d',
    stable: 'Tiny Hooves Sanctuary',
    distance: 4,
    bio: 'Small. Fluffy. Absolutely in charge. I have bitten exactly one farrier and he deserved it.',
    interests: ['Being in charge', 'Snacks', 'Tiny hats', 'Naps in the sun'],
    gait: 'Walk',
    lookingFor: 'Someone who respects the pony',
  },
  {
    id: 'h14',
    name: 'Willow',
    age: 7,
    sex: 'Mare',
    breed: 'Irish Sport Horse',
    height: 16.2,
    coat: '#4a4a4f',
    mane: '#1a1a1c',
    stable: 'Greenhill Eventing',
    distance: 14,
    bio: 'Three-day eventer. Cross-country is my love language. Water jumps do not scare me, but plastic bags might.',
    interests: ['Eventing', 'Jumping', 'Mud baths', 'Adrenaline'],
    gait: 'Canter',
    lookingFor: 'Brave and bold',
  },
  {
    id: 'h15',
    name: 'Domino',
    age: 9,
    sex: 'Gelding',
    breed: 'Clydesdale',
    height: 17.2,
    coat: '#3b2314',
    mane: '#1c100a',
    stable: 'Heritage Hitch Barn',
    distance: 19,
    bio: 'Feathered feet, big heart. I have been in a commercial. I do not like to talk about it.',
    interests: ['Parades', 'Pulling stuff', 'Oats', 'Belly rubs'],
    gait: 'Walk',
    lookingFor: 'A gentle soul',
  },
  {
    id: 'h16',
    name: 'Starlight',
    age: 4,
    sex: 'Mare',
    breed: 'Morgan',
    height: 14.3,
    coat: '#2c1a10',
    mane: '#120a05',
    stable: 'North Star Farm',
    distance: 11,
    bio: 'Compact, clever, and a little bit vain about my neck arch. I can do anything and I usually do.',
    interests: ['Driving', 'Trail rides', 'Apples', 'Showing off'],
    gait: 'Trot',
    lookingFor: 'Versatile and fun',
  },
];

// Canned replies that matched horses send back in chat.
export const HORSE_REPLIES = [
  'Neigh! So glad we matched. What is your favorite kind of hay?',
  'Do you prefer the left side of the pasture or the right? This is important.',
  'I just rolled in the mud and I feel amazing. You?',
  'My human brought carrots today. I saved you one. (I ate it. Sorry.)',
  'Wanna meet at the water trough later?',
  'Be honest: apples or peppermints?',
  'I heard a plastic bag earlier and I am still recovering.',
  'Race you to the far fence?',
  'The farrier is coming tomorrow. Thoughts and prayers.',
  'You have a lovely mane. I noticed it right away.',
  '*whinnies softly*',
  'What is your stance on being ridden? Asking for a friend.',
  'I found the good grass. I will show you where. Nobody else knows.',
];
